import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'

import "~/styles/globals.css";
import { TopNav } from "./_components/TopNav";
import "@uploadthing/react/styles.css";
// If '@uploadthing/react/server' does not exist, try importing from '@uploadthing/react' instead:
import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
import { extractRouterConfig } from "uploadthing/server";
// Import your file router (adjust the path as needed)

import { type Metadata } from "next";
import { Geist } from "next/font/google";
import { ourFileRouter } from './api/uploadthing/core';
import type React from 'react';

export const metadata: Metadata = {
  title: "T3 Gallery",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};



const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
  modal,
}: { 
  children: React.ReactNode;
  modal: React.ReactNode;
 }) {
  return (
    <ClerkProvider>
      <html lang="en" className={`${geist.variable} flex flex-col gap-4`}>
        <NextSSRPlugin
          /**
           * The `extractRouterConfig` will extract **only** the route configs
           * from the router to prevent additional information from being
           * leaked to the client. The data passed to the client is the same
           * as if you were to fetch `/api/uploadthing` directly.
           */
          routerConfig={extractRouterConfig(ourFileRouter)}
        />
        <body className={`font-sans ${geist.variable}`}>
          <div id="modal-root" />
          <TopNav />
           
          {children}
          {modal}
        </body>
      </html>
    </ClerkProvider>
  );
}
